"""Built-in background music.

Bundling real music would be a licensing problem, so instead we synthesize
simple ambient pads with ffmpeg's own oscillators. They are generated by this
code, so they are yours to use commercially with no attribution.

Users can always upload their own track, which overrides this entirely.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

from config import settings
from ffmpeg_utils import run

LOOP_SECONDS = 32

# Chord voicings in Hz. Kept in the low-mid range so speech sits above them.
MOODS: dict[str, dict] = {
    "calm": {
        "freqs": [110.0, 164.81, 220.0, 261.63],   # A2 E3 A3 C4  (A minor)
        "lowpass": 900,
        "tremolo": (0.12, 0.35),
    },
    "uplifting": {
        "freqs": [130.81, 196.0, 261.63, 329.63],  # C3 G3 C4 E4  (C major)
        "lowpass": 1400,
        "tremolo": (0.18, 0.28),
    },
    "cinematic": {
        "freqs": [73.42, 110.0, 146.83, 220.0],    # D2 A2 D3 A3  (D drone)
        "lowpass": 700,
        "tremolo": (0.10, 0.45),
    },
    "warm": {
        "freqs": [98.0, 146.83, 196.0, 246.94],    # G2 D3 G3 B3  (G major)
        "lowpass": 1100,
        "tremolo": (0.12, 0.30),
    },
}

DEFAULT_MOOD = "calm"


async def get_bgm(mood: str) -> Path:
    """Return a cached 32-second loop for `mood`, generating it on first use."""
    mood = mood if mood in MOODS else DEFAULT_MOOD
    spec = MOODS[mood]

    cache_dir = settings.assets_dir / "bgm"
    cache_dir.mkdir(parents=True, exist_ok=True)
    key = hashlib.md5(f"{mood}-{spec}-{LOOP_SECONDS}".encode()).hexdigest()[:10]
    out = cache_dir / f"{mood}-{key}.wav"
    if out.exists():
        return out

    cmd: list[str] = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error"]
    for f in spec["freqs"]:
        cmd += ["-f", "lavfi", "-i", f"sine=frequency={f}:duration={LOOP_SECONDS}"]

    n = len(spec["freqs"])
    # ffmpeg's tremolo rejects frequencies below 0.1 Hz - clamp rather than crash.
    tre_f, tre_d = spec["tremolo"]
    tre_f = max(0.1, float(tre_f))
    # Detune each voice slightly so the pad breathes instead of sounding static.
    voices = "".join(
        f"[{i}:a]vibrato=f={3.0 + i * 0.7}:d=0.08,volume={0.9 - i * 0.12:.2f}[v{i}];"
        for i in range(n)
    )
    mix_in = "".join(f"[v{i}]" for i in range(n))
    graph = (
        voices
        + f"{mix_in}amix=inputs={n}:normalize=1[mix];"
        + f"[mix]tremolo=f={tre_f}:d={tre_d},"
        + f"lowpass=f={spec['lowpass']},"
        + "aecho=0.8:0.88:500|900:0.35|0.22,"
        + f"afade=t=in:st=0:d=3,afade=t=out:st={LOOP_SECONDS - 3}:d=3,"
        + "volume=0.9,"
        + "aformat=sample_fmts=s16:sample_rates=44100:channel_layouts=stereo[out]"
    )

    cmd += [
        "-filter_complex", graph,
        "-map", "[out]",
        "-t", str(LOOP_SECONDS),
        str(out),
    ]
    await run(cmd, timeout=180)
    return out
